# Generated by Django 3.1.7 on 2021-03-21 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('brand', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('hex', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('sg_id', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('sq_ft', models.FloatField()),
                ('p_lot', models.BooleanField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movement', models.FloatField()),
                ('closed_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sc_app.info')),
                ('open_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sc_app.info')),
            ],
        ),
        migrations.CreateModel(
            name='Closed',
            fields=[
                ('name', models.TextField(max_length=3, primary_key=True, serialize=False)),
                ('sg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sc_app.info')),
            ],
        ),
    ]
