# Generated by Django 3.1.7 on 2021-03-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='yr',
            field=models.IntegerField(default=0),
        ),
    ]
