# Generated by Django 3.1.7 on 2021-03-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0003_auto_20210321_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closed',
            old_name='sg_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='info',
            name='brand',
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.ForeignKey(default='Target', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sc_app.colors'),
            preserve_default=False,
        ),
    ]
