# Generated by Django 3.1.7 on 2021-03-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0004_auto_20210321_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closed',
            options={'verbose_name_plural': 'Closed'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Info'},
        ),
    ]
