# Generated by Django 3.1.7 on 2021-03-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0006_cbginfo_cbgstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbginfo',
            name='asian',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cbginfo',
            name='bachelor_degree',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cbginfo',
            name='black',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cbginfo',
            name='hispanic',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cbginfo',
            name='med_hh_income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cbginfo',
            name='population',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cbginfo',
            name='white',
            field=models.FloatField(default=0),
        ),
    ]
