# Generated by Django 3.1.7 on 2021-03-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0007_auto_20210324_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbginfo',
            name='med_hh_income',
            field=models.FloatField(default=0, null=True),
        ),
    ]
