# Generated by Django 3.1.7 on 2021-04-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0009_auto_20210324_0310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CbgStore',
        ),
    ]
