# Generated by Django 3.1.7 on 2021-04-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0010_delete_cbgstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbgStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_visit_18', models.FloatField(default=0.0)),
                ('percent_visit_19', models.FloatField(default=0.0)),
                ('num_visit_18', models.IntegerField(default=0)),
                ('num_visit_19', models.IntegerField(default=0)),
                ('percent_visit_brand_18', models.FloatField(default=0.0)),
                ('percent_visit_brand_19', models.FloatField(default=0.0)),
                ('num_visit_brand_18', models.IntegerField(default=0)),
                ('num_visit_brand_19', models.IntegerField(default=0)),
                ('pop_near_store', models.FloatField(default=0.0)),
                ('dist_store_cbg', models.FloatField(default=0.0)),
                ('poi_near_store', models.IntegerField(default=0)),
                ('diversity_near_store', models.FloatField(default=0.0)),
                ('demo_similarity', models.FloatField(default=0.0)),
                ('med_inc_near_store', models.FloatField(default=0.0)),
                ('cbgID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sc_app.cbginfo')),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sc_app.info')),
            ],
        ),
    ]
