# Generated by Django 3.1.7 on 2021-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0011_cbgstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbgstore',
            name='demo_similarity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='dist_store_cbg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='diversity_near_store',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='med_inc_near_store',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='num_visit_18',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='num_visit_19',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='num_visit_brand_18',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='num_visit_brand_19',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='percent_visit_18',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='percent_visit_19',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='percent_visit_brand_18',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='percent_visit_brand_19',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='poi_near_store',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='pop_near_store',
            field=models.FloatField(),
        ),
    ]
