# Generated by Django 3.1.7 on 2021-04-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0012_auto_20210429_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbgstore',
            name='num_visit_18',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cbgstore',
            name='num_visit_19',
            field=models.IntegerField(),
        ),
    ]
