# Generated by Django 3.1.7 on 2021-04-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0014_auto_20210429_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CbgInfo',
        ),
        migrations.DeleteModel(
            name='CbgStore',
        ),
    ]
