# Generated by Django 3.1.7 on 2021-04-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0015_auto_20210429_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cbgs',
            fields=[
                ('cbgID', models.IntegerField(primary_key=True, serialize=False)),
                ('population', models.IntegerField()),
                ('median_income', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CbgStore',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('percent_visit', models.FloatField()),
                ('number_visits', models.IntegerField()),
                ('pop_near_store', models.FloatField()),
                ('dist_store_cbg', models.FloatField()),
                ('store_area', models.IntegerField()),
                ('p_lot', models.BooleanField()),
                ('poi_near_store', models.IntegerField()),
                ('diversity_near_store', models.FloatField()),
                ('demo_similarity', models.FloatField()),
                ('med_inc_near_store', models.FloatField()),
                ('brand', models.CharField(max_length=80)),
                ('num_visit_brand', models.IntegerField()),
                ('percent_visit_brand', models.FloatField()),
                ('year', models.IntegerField()),
                ('cbgID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sc_app.cbgs')),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sc_app.info')),
            ],
        ),
    ]
